variable "project" {}
variable "region" {}
variable "namespace" {}
variable "tfe_license_name" {}
#variable "tfe_license_path" {}
variable "tfe_license_secret_id" {}
variable "fqdn" {}
variable "ssl_certificate_name" {}
variable "dns_zone_name" {}
variable "database_availability_type" {}